### ISSUE TITLE
Script fails at handling spaces in path to build /derived data directories

### ISSUE THREAD

**Issue by deszip** [PaulTaykalo/objc-dependency-visualizer#14]
This issue is easy to reproduce if your project name contains spaces

**Comment by PaulTaykalo** [comment]
@deszip Can you give me an example of output when this thing happens?

**Comment by deszip** [comment]
Sure
https://gist.github.com/deszip/a9053a209fc2d9f920a3

**Comment by PaulTaykalo** [comment]
@deszip for now, until it will be fixed, running without `-d` should help

**Comment by PaulTaykalo** [comment]
should be fixed in #15

**Comment by deszip** [comment]
-d -p works great:
http://cl.ly/image/1e1Q3L3E3j1b

thanks
