### ISSUE TITLE
origin.js file does not seem to be closed correctly

### ISSUE THREAD

**Issue by klausbussekw** [PaulTaykalo/objc-dependency-visualizer#22]
Environment: OS X 10.11.2

The origin file does not seem to be closed in the end. OS X Finder shows the file with a size of zero bytes after running the script. Duplicating the origin.js in Finder rectifies this.

**Comment by PaulTaykalo** [comment]
It has nothing to do with dep vis itself, it's how OSX works with redirection of output to file.
If you really want to see actual result, you can add `touch origin.js` as the last part of script

**Comment by klausbussekw** [comment]
Thanks a lot!

**Comment by PaulTaykalo** [comment]
Will check this one then
