### ISSUE TITLE
How to exclude test classes?

### ISSUE THREAD

**Issue by derpoliuk** [PaulTaykalo/objc-dependency-visualizer#25]
Thank you for this nice tool. Is there any way to exclude classes from test target?

**Comment by PaulTaykalo** [comment]
Well, first of all, I don't know what test classes are doing in your non-test taget :)
dep-vis tries to search for a project files, which shouldn't be test-classes.
If you're just getting test target got visualized, then you can just change a bit of your non-test target, and then try to build it and re-run dep-vis.
If this won't help - you can try to put `-p` option and provide a path to the obj files
If this won't help - write here what kind of project you're trying to build, and what configuration do you have

**Comment by derpoliuk** [comment]
Thank you for feedback. 

Strange but it's working now. Probably I ran tests before visualizing dependencies 4 days ago.

Thanks again!
