### ISSUE TITLE
Exclude nodes that don't have outgoing edges

### ISSUE THREAD

**Issue by eaigner** [PaulTaykalo/objc-dependency-visualizer#26]
In large projects with many classes this graph can get quite messy. It would help if there was an option to eliminate nodes that only have one incoming edge and no outgoing ones.

**Comment by PaulTaykalo** [comment]
@eaigner Could you give a screen shot of those? Don't know if this will help. But some filtering will be good to have

**Comment by PaulTaykalo** [comment]
closed due to inactivity
