### ISSUE TITLE
[feature] Multiple obj files location support

### ISSUE THREAD

**Issue by dodikk** [PaulTaykalo/objc-dependency-visualizer#27]
**As** a [sub-project](https://www.cocoanetics.com/2011/12/sub-projects-in-xcode/) approach user
**I'd like** to specify multiple location of *.obj files
**So that** business logic files contained in a sub-project is displayed in the graph.

It would be cool to easily switch between the "single project" mode (as is) and "all `*.obj` files in DerivedData" to get the desired level of report granularity.

**Comment by PaulTaykalo** [comment]
@dodikk Bump.
As about multiple sub-project thing It's good to have an example of this kind of project and your expectations on this :+1:

**Comment by dodikk** [comment]
>> It's good to have an example of this kind of project

https://github.com/dodikk/weather-iasync
You can use this one. It's based on static libs and sub-projects.

>> your expectations on this

1. Both GUI classes (from main project) and business logic classes (from libs) are visualised.
2. There should be an option to generate the report "as is" (only GUI classes).

**Comment by PaulTaykalo** [comment]
@dodikk Take a look here https://github.com/PaulTaykalo/objc-dependency-visualizer/wiki/Usage-examples#dependencies-generated-from-specific-targets-t1-and-t2-of-project-with-name-x
In this specific case, the command could look like
`./generate-objc-dependencies-to-json.rb -e "NS|UI|CA|KW|CF|RAC" -d -t "iAsyncWeatherOperations" -t "JFFAsyncOperations" > origin.js`

**Comment by dodikk** [comment]
Thanks. It works.
Great job.

**Comment by dodikk** [comment]
It would be cool to have some **auto detection** feature in order to **not maintain** the list of `-t` arguments **manually**.
Still, I the `xcodebuild -list` and editing the generation script manually approach is ok for now.

**Comment by PaulTaykalo** [comment]
@dodikk the tool itself doesn't care where dependencies are coming from, so I would suggest to have small additional script like `xcodebuild --list` and pass parameters from it to dep visualizer
