### ISSUE TITLE
origin.js is empty

### ISSUE THREAD

**Issue by fangborui** [PaulTaykalo/objc-dependency-visualizer#58]
I have a pod project named kepler4iphone
and I user your tool to execute scentence like below:

1、clone it into my folder
2、execute ./generate-objc-dependencies-to-json.rb -d -s "kepler4iphone" > origin.js ;
console shows:
find: /Users/frank/Library/Caches/appCode*/DerivedData: No such file or directory
There were 24 directories found
Last modifications were in
/Users/frank/Library/Developer/Xcode/DerivedData/kepler4iphone-fpjlrpkkpaulyydolpctvygupltl/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/WeexResKit.build/Objects-normal/armv7
directory at
2018-09-12 12:15:24 +0800

3、nothing in origin.js

**Comment by fangborui** [comment]
of cause , I build my project

**Comment by fangborui** [comment]
does it can't work in XCode 9.3 ？

**Comment by PaulTaykalo** [comment]
@fangborui It searches items in Pods Doesn't work with pods.
you can specify path to your project objects via *-p* option
https://github.com/PaulTaykalo/objc-dependency-visualizer/wiki/Usage-examples#from-object-files

as a workaround - change something in your project and compile again. Script by default checks the latest changed directory. In your case it's Pods proejct. It shoudl be your project instaed
