### ISSUE TITLE
How to filter categories?

### ISSUE THREAD

**Issue by sebastianwr** [PaulTaykalo/objc-dependency-visualizer#8]
The README says that you can filter classes and I found the removal of certain prefixes, but is it also possible to filter out categories from the dependency graph?

Aside from that: Outstanding tool, really appreciate your work!

**Comment by PaulTaykalo** [comment]
Well it's hard to tell whether it's category or not.
We can only probably tell it, based on the filename, but it wouldn't be 100% perfect.

**Comment by sebastianwr** [comment]
That's true. But if you stick to a convention, then probably every category has a + inside the filename and any other class doesn't!? Still not perfect, but enough for some (i.e. me ;-) )
