### ISSUE TITLE
No graph is generated.

### ISSUE THREAD

**Issue by Codeido** [PaulTaykalo/objc-dependency-visualizer#9]
Hello.

I have a problem with the plugin. I installed it correctly. Runs correctly and generates me the files, but when I open the file "index" in the browser, there is no graphic inside.

I tried with several Xcode projects, but nothing changes.

My Xcode version is 6.1.1

**Comment by PaulTaykalo** [comment]
How do you run generator, and what is output?  
Does the path, in the output looks correct?

**Comment by Codeido** [comment]
I start the generator from the menu of Xcode. The output is a folder in the xcode project, with the files inside it.

Screenshots:
http://cl.ly/image/293V3U3y382F
http://cl.ly/image/3A3f0b0s1d3c

The path looks correct.
This is the result when i open index.html:
http://cl.ly/image/2B3C3x3a1Z2Y

**Comment by PaulTaykalo** [comment]
heh :) I would recoomend to pass these issues about plugin you're using to the maintainer of the Xcode plugin :)
I think that you've used https://github.com/kimsungwhee/KSHObjcUML this one.  
As far as I understand it's just wrapper over the `generate-objc-dependencies-to-json.rb` script.  
I need an output of that script to help you :)

**Comment by Codeido** [comment]
This is the entire ObjcUML folder: http://cl.ly/381v17093v34

**Comment by PaulTaykalo** [comment]
From what I see there - there's no `origin.js` file.  
So I suppose it wasn't generated by **plugin**. So it's better to address this issue to this guy: https://github.com/kimsungwhee/KSHObjcUML

**Comment by Codeido** [comment]
Ok I try. Thank You

**Comment by PaulTaykalo** [comment]
You can try to run this tool without plugin and see the results:) I think it will be better to https://github.com/kimsungwhee/KSHObjcUML if you'll have some results. By this you'll be sure that this is plugin's problem, and not tool's:)
